- .vscode/settings.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/config/i18n.ts
- frontend/src/locales/en.json
- frontend/src/locales/fr.json
- frontend/src/locales/ja.json
- frontend/src/main.ts
- frontend/src/models/Lang/repository.ts
- frontend/src/models/User/repository.ts
- frontend/src/pages/Home/index.html
- frontend/src/pages/Home/index.ts
- frontend/src/pages/Home/style.css
- frontend/src/pages/Login/index.html
- frontend/src/pages/Login/index.ts
- frontend/src/pages/Login/style.css
- frontend/src/pages/Register/index.html
- frontend/src/pages/Register/index.ts
- frontend/src/pages/Register/style.css
ログイン画面とユーザー登録画面、Welcomeページに言語選択ボタンを追加
- ログイン画面を言語選択可能に
- ユーザー登録画面を言語選択可能に
- Welcom画面を言語選択可能に
上記ページたち
Welcomeページにアクセスし、ログインしてみる
- 関連Issue: #95
> ADD: 多言語対応 #95

- frontend/src/config/i18n.ts
- frontend/src/models/User/repository.ts
- frontend/src/models/Window/repository.ts
- frontend/src/models/interface.ts
- frontend/src/pages/404/index.ts
- frontend/src/pages/Friends/index.ts
- frontend/src/pages/Home/index.ts
- frontend/src/pages/Leaderboard/index.ts
- frontend/src/pages/Login/index.ts
- frontend/src/pages/Logout/index.ts
- frontend/src/pages/Modes/index.ts
- frontend/src/pages/Profile/index.ts
- frontend/src/pages/Register/index.ts
- frontend/src/pages/Result/index.ts
- frontend/src/pages/Settings/User/index.ts
- frontend/src/pages/SinglePlay/Game/logic.ts
- frontend/src/pages/SinglePlay/Select/index.ts
- frontend/src/utils/form.ts
- frontend/src/utils/language.ts
- frontend/src/utils/togglePassword.ts
まだリファクタリングします！
- FIX: Interfaceを統一 #186
- FIX: updatePageContentの処理を統一&全体反映 #183
front全域
全体的な動作確認
- 関連Issue: #183 
- 関連Issue: #186
> FIX: リファクタリング PART 3 #135

- frontend/src/pages/Result/index.ts
- frontend/src/pages/SinglePlay/Game/Ball.ts
- frontend/src/pages/SinglePlay/Game/Experience.ts
- frontend/src/pages/SinglePlay/Game/Field.ts
- frontend/src/pages/SinglePlay/Game/LocalGame.ts
- frontend/src/pages/SinglePlay/Game/index.html
- frontend/src/pages/SinglePlay/Game/index.ts
- frontend/src/pages/SinglePlay/Game/style.css
- frontend/src/pages/SinglePlay/Select/index.html
- package-lock.json
- package.json
・GAME START
・GAME OVER
・YOU WIN!
・SCORE　の表示
・CPU3段階レベル別ロジック追加
・ゲーム開始、終了時の挙動追加。
・EASY, MEDIUM, HARD, 鬼 4レベルに応じたBallとPaddleの速度を設定。
- 関連Issue: #215 #216 #188
> Hrinka2/add show result#215

- frontend/src/core/Page.ts
- frontend/src/models/Result/GameResultService.ts
- frontend/src/pages/MultiPlay/Game/index.ts
- frontend/src/pages/Tournament/Game/index.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> fix type error

- ELK/setup/entrypoint.sh
- ELK/setup/policies/logs_policy.json
- ELK/setup/templates/logs_template.json
- docker-compose.elk.yml
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> add template

- frontend/src/pages/Result/index.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> スコア重複問題 修正

- api/pong/fixtures/initial_data.json
- api/pong/game_logic.py
- api/pong/tournament_consumers.py
- frontend/src/pages/Tournament/Waiting/index.html
- frontend/src/pages/Tournament/Waiting/index.ts
- frontend/src/pages/Tournament/Waiting/style.css
いったんウェイティング画面まで
ウェイティング用のウェブソケットクラスと画面の整備
- ブラウザ4つでジョインしてみる
- 離脱したりしてバグらないか確認する
- データベースにアクセスして正しく登録できているか確認する
- 関連Issue: #212
> ADD: トーナメントのwaiting#212

- api/pong/views.py
- frontend/src/pages/Settings/User/index.ts
- frontend/src/utils/fetcher.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> fix 画像登録できるように

- frontend/src/libs/Auth/currnetUser.ts
> FIX: ウェルカムページにアクセスできず、loginへ強制遷移する #256

- frontend/src/models/User/repository.ts
- frontend/src/pages/Profile/index.html
- frontend/src/pages/Profile/index.ts
- frontend/src/pages/Profile/style.css
> FIX: プロファイルページのフォーマット修正 #259

- frontend/src/pages/Modes/index.ts
- frontend/src/pages/Modes/style.css
> FIX: /modesでトーナメントのボタンが押下できない #264

- api/pong/modules/Auth/views.py
- frontend/src/layouts/common/style.css
- frontend/src/locales/en.json
- frontend/src/locales/fr.json
- frontend/src/locales/ja.json
- frontend/src/pages/Modes/index.html
- frontend/src/pages/Modes/index.ts
- frontend/src/pages/Modes/style.css
MODE select画面で42ボタンが反応しない #274問題を解決
- 関連Issue: #274
> MODE select画面で42ボタンが反応しない #274

- ELK/elasticsearch/Dockerfile
- ELK/kibana/Dockerfile
- ELK/logstash/Dockerfile
- ELK/setup/Dockerfile
- docker-compose.elk.yml
```
$ make re
```
`https://{IPアドレス}:3001/`
↓
http://127.0.0.1:5601/app/discover
"message":"HomePage mounted!"
が出るとOK
> ELK バインドボリューム使えない問題

- frontend/src/locales/en.json
- frontend/src/locales/fr.json
- frontend/src/locales/ja.json
- frontend/src/pages/Home/index.ts
- frontend/src/pages/Modes/index.ts
- frontend/src/pages/Profile/index.html
- frontend/src/pages/Profile/index.ts
- frontend/src/pages/Settings/User/index.ts
- frontend/src/pages/SinglePlay/Select/index.html
- frontend/src/pages/SinglePlay/Select/index.ts
- frontend/src/utils/updateElements.ts
single, multi, tournament以外のページの多言語対応およびバグ修正
- 関連Issue: #277 
- 関連Issue: #276 
- 関連Issue: #278
> ADD: 多言語対応 #280

- Makefile
- frontend/src/pages/SinglePlay/Game/LocalGame.ts
- frontend/src/pages/SinglePlay/Game/index.ts
シングルプレイCPUのアルゴリズムを弱体化する
基本的に関数一個しかいじりません。
なし
シングルプレイで適度に点が取れるか
- 関連Issue: #290
> UPDATE: シングルプレイのAI弱体化計画 #290

- frontend/src/layouts/common/index.html
- frontend/src/layouts/common/index.ts
- frontend/src/layouts/common/style.css
- frontend/src/pages/Modes/style.css
- frontend/src/pages/Profile/Background.ts
- frontend/src/pages/Profile/index.html
- frontend/src/pages/Profile/index.ts
- frontend/src/pages/Profile/style.css
- frontend/src/pages/SinglePlay/Game/LocalGame.ts
- frontend/src/pages/SinglePlay/Game/index.ts
- frontend/src/pages/SinglePlay/Game/style.css
GAME START中に1.5秒待機
・GAME START中に1.5秒待機
・layouts/commonでフォント設定
・top-bar色変更
・profile pageの背景
> Hrinka2/fix loading#291

- frontend/src/pages/SinglePlay/Game/style.css
game画面において
・customization-panelとpause-buttonのx軸とサイズを調整
  ・pause-buttonとscore-display のy軸とサイズを調整
cssの、ミリ単位で位置変更
> FIX: Game css

- frontend/src/pages/Profile/index.html
- frontend/src/pages/Profile/style.css
> rescue lost pencil#306

- frontend/src/models/Game/repository.ts
- frontend/src/models/interface.ts
- frontend/src/pages/Home/Background.ts
- frontend/src/pages/Home/Background2.ts
- frontend/src/pages/Home/index.ts
- frontend/src/pages/Profile/index.ts
- frontend/src/pages/SinglePlay/Game/Utils/EventEmitter.ts
- frontend/src/pages/Tournament/Waiting/index.ts
- frontend/src/utils/fetcher.ts
- frontend/src/utils/form.ts
lintのエラーを解消する
frontend配下
フロント全体
すべての画面が動くか
- 関連Issue: #287
> FIX: make lintがえぐいことになっている #287

- frontend/src/models/User/repository.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> displayname変わらない問題

- frontend/src/pages/SinglePlay/Game/Experience.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> logger うるさい

- frontend/src/pages/SinglePlay/Game/Experience.ts
¥
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> delete loffer import

- frontend/src/pages/SinglePlay/Game/Ball.ts
- frontend/src/pages/SinglePlay/Game/CustomParticle.ts
- frontend/src/pages/SinglePlay/Game/Field.ts
- frontend/src/pages/SinglePlay/Game/LocalGame.ts
- frontend/src/pages/SinglePlay/Game/Utils/Loaders.ts
- frontend/src/pages/SinglePlay/Game/World/Camera.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> fix logger うるさい

- frontend/src/models/Game/repository.ts
- frontend/src/pages/SinglePlay/Game/LocalGame.ts
- 変更点1
- 変更点2
- 変更点3
- テストケース1
- テストケース2
- テストケース3
> やさしいレベル選択した時戦歴に残らない
